-- auto-generated definition
create table pupil
(
    id                    integer generated by default as identity
        primary key,
    class_number          integer,
    create_date           timestamp,
    date_of_birth         timestamp    not null,
    date_of_record        timestamp    not null,
    how_to_know           varchar(255),
    last_name             varchar(255) not null,
    modify_date           timestamp,
    mother_name           varchar(255),
    name                  varchar(255) not null,
    second_name           varchar(255) not null,
    telephone             varchar(11)  not null,
    created_by            bigint       not null,
    update_by             bigint,
    deleted               boolean default false,
    telephone_responsible varchar(11)
);

alter table pupil
    owner to admin;

ALTER SEQUENCE pupil_id_seq
    RESTART WITH 237;
